# Generated by Django 6.0.4 on 2026-04-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
